name: Deployment 

on:
  push:
    branches:
      - master

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo"i'm running a dev slot
  
  QA:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo"i'm running a qa slot
